security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        Symfony\Component\Security\Core\User\User: 'bcrypt'
    providers:
        in_memory:
            memory:
                users:
                    tadming:
                        password: $2y$13$cAq.cY1SSiPtkqlF.2Pv4O0YiQ0DIfpVMAEiXrbuF.wfOjP0fvc1a
                        roles: 'ROLE_ADMIN'
                        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:      .*
            provider: in_memory
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   /logout
                target: /
            anonymous:    true

    access_control:
        - { path: ^/api/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/images/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }
